{{- $kafkaServiceName := printf "%s.%s.svc.cluster.local:9092" "degressly-kafka" .Release.Namespace -}}
{{- $primaryServiceName := printf "http://degressly-subject-%s-service.%s.svc.cluster.local" (index .Values.subjectNames 0) .Release.Namespace -}}
{{- $secondaryServiceName := printf "http://degressly-subject-%s-service.%s.svc.cluster.local" (index .Values.subjectNames 1) .Release.Namespace -}}
{{- $candidateServiceName := printf "http://degressly-subject-%s-service.%s.svc.cluster.local" (index .Values.subjectNames 2) .Release.Namespace -}}

apiVersion: v1
kind: Secret

metadata:
  name: degressly-secrets
type: Opaque
data:
  spring_profiles_active: {{ "mongo" | b64enc | quote }}
  diff_publisher_bootstrap_servers: {{ $kafkaServiceName | b64enc | quote }}
  diff_publisher_topic_name: {{ "diff_stream" | b64enc | quote }}
  primary_host: {{ $primaryServiceName | b64enc | quote }}
  secondary_host: {{ $secondaryServiceName | b64enc | quote }}
  candidate_host: {{ $candidateServiceName | b64enc | quote }}
  MONGO_URL: {{ "degressly-mongo:27017/degressly" | b64enc | quote }}
  MONGO_USERNAME: {{ "degressly_user" | b64enc | quote }}
  MONGO_PASSWORD: {{ "secure_password" | b64enc | quote }}
  MONGO_DBNAME: {{ "degressly" | b64enc | quote }}
  return_response_from: {{ "PRIMARY" | b64enc | quote }}
  proxy_service_type: {{ "IDEMPOTENT_DOWNSTREAM" | b64enc | quote }}
  degressly_downstream_observation_use_request_uri: {{ "true" | b64enc | quote }}
  replay_consumer_bootstrap_servers: {{ $kafkaServiceName | b64enc | quote }}
  degressly_downstream_host: {{ "http://asd" | b64enc | quote }}
  replay_consumer_topic_name: {{ "replay" | b64enc | quote }}
  replay_consumer_group_id: {{ "replay_default" | b64enc | quote }}
